### ISSUE TITLE
환경 구축 스크립트 버그

### ISSUE THREAD

**Issue by KIMBIBLE** [0peratingSystem/Operating-System#30]
ubuntu 16.04 환경에서 scripts/install_ubuntu16.sh 실행 시,

qemu 소스코드 build 과정에서 required package version conflict error 발생.

**Comment by KoreaSecurity** [comment]
![image](https://user-images.githubusercontent.com/8425791/77079107-d9074080-6a3a-11ea-99f8-f645204ea1c4.png)

환경설정 시 필요한 패키지가 설치되어 있지 않아, configure error로 인해 발생하는 문제로 생각됩니다.

해당 이슈는 가상화 환경을 QEMU 4.2.0으로 통일이 확정되면, 수정하도록 하겠습니다. :)

**Comment by KIMBIBLE** [comment]
7b31e61249b868a165f9a552a023d6e54c32e497 기점으로 컨테이너 기반 통합 빌드 환경 구성이 완료되어 해당 issue close.
