### ISSUE TITLE
[추가 개발계획]  소스코드 빌드 자동화 프레임 워크 

### ISSUE THREAD

**Issue by KoreaSecurity** [0peratingSystem/Operating-System#34]
컨테이너를 활용한 소스코드 빌드 자동화 프레임워크 프로토 타입을 20.03.26 업로드 하였습니다.
[작업내역]
1. koreasecurity/dev:os_dev 업데이트
2. 개발환경 구동 후 Build
3. 빌드 이후 Image File Copy

향후 추가될 기능은 아래와 같습니다.

1.  개인 Branch 연동 기능 (Git 확장)
2.  Remote 개발 환경 연동 기능
3.  프레임워크 구조 설계

![image](https://user-images.githubusercontent.com/8425791/77625299-b15a3000-6f86-11ea-8b20-ea6015fe328b.png)

**Comment by KoreaSecurity** [comment]
[2020.04.07] ADD Function
source_copy: 컨테이너 내부에 소스코드 업데이트 (경로 Operating-System 또는 .)
termcolor : Color 추가
status_check: 이전에 구동되었지만 종료된 컨테이너가 있으면 재시작

**Comment by KIMBIBLE** [comment]
7b31e61249b868a165f9a552a023d6e54c32e497 기점으로 통합 빌드 환경 구성 완료
