### ISSUE TITLE
floppy sector's 크기로 인한 이미지 로드 에러 문제

### ISSUE THREAD

**Issue by KoreaSecurity** [0peratingSystem/Operating-System#55]
![image](https://user-images.githubusercontent.com/8425791/79176704-e944ec80-7e3b-11ea-8b1c-15b7a6fded32.png)
1. 책에서는 위와 같이 항상 섹터가 18개라고 가정하고, 섹터크기를 18개로 거장하여 부트로더를 구현하였음 
2. 하지만, floppy의 사이즈가 1.44MB 일떄는 18개 이지만  2.88MB일떄는 36개로 섹터가 늘어남
![image](https://user-images.githubusercontent.com/8425791/79177163-1c3bb000-7e3d-11ea-95ee-9e2ef2e8fdbf.png)

3. QEMU 1.x 이후 버전부터는 Default floppy 크기가 상이함 (Windows 2.88MB, MAC 1.44MB) 

![image](https://user-images.githubusercontent.com/8425791/79177430-c0255b80-7e3d-11ea-9aca-4c850fdc024e.png)

4. 따라서 Windows 환경에서는 Bootloader.asm의 섹터 체크하는 부분을 37로 수정해줘야 정상적으로 동작함 (13장)

**Comment by ghost** [comment]
하나 궁금한 점이 있는데, 3번 항목에 QEMU 1.x 이후에서 운영체제에 따라서 Default floppy 크기가 상이하다고 적혀있습니다. 그렇다는 말씀은 qemu가 하이퍼바이저 외부의 host os를 구분하는 기능이 있다고 할 수 있는건가요?

**Comment by zj3t** [comment]
흠...이 부분은 좀더 알아봐야겠지만, Host OS에서 지원되는 하이퍼바이저 옵션(?)이라해야할지 그거에 따라 구분하는 기능이 있을 껏 같은데...정확한 건 소스코드를 봐야할 것같네요..

**Comment by KIMBIBLE** [comment]
Solved at Issue #57
