### ISSUE TITLE
build script 실행시 컨테이너 디폴트 이미지에 내장된 Disk.img 파일이 복사되는 버그

### ISSUE THREAD

**Issue by KIMBIBLE** [0peratingSystem/Operating-System#57]
빌드 스크립트(AutoBuild_macOS.py Auto_Build_Prototype.py) 실행 시, 컨테이너 이미지를 처음 생성한 경우 컨테이너 디폴트 이미지에 내장된 Disk.img 파일이 복사되는 버그 발생.

**Comment by KIMBIBLE** [comment]
디스크 이미지 생성 시점과 카피 시점의 머징 과정 딜레이 때문에 발생.

**Comment by zj3t** [comment]
이게 그 회의때 docker cp 이용하기로했던 부분인가?

**Comment by KIMBIBLE** [comment]
> 이게 그 회의때 docker cp 이용하기로했던 부분인가?

맞음. 해결해서 풀리퀘스트(#58 ) 보내 놓은 상태.

**Comment by KIMBIBLE** [comment]
@KoreaSecurity @yibyeongyong @Rye713  ubuntu 환경에서 빌드 자동화 스크립트`Auto_Build_Prototype.py` 에도 동일한 버그가 발생하면 해당 부분 코드 수정해야 할 것 같습니다.

**Comment by ghost** [comment]
> 
> 
> 디스크 이미지 생성 시점과 카피 시점의 머징 과정 딜레이 때문에 발생.

제가 제대로 이해한 것인지 모르겠지만, 디스크 이미지 생성 시간이, auto_build 소스코드가 카피를 수행하는 시점까지 도달하는데 걸리는 시간보다 오래걸리기 때문에 버그가 발생한다는 말씀이시죠?

그렇다면 docker cp를 해도 결과는 똑같을 것같은데... 문제가 해결되는게 신기하네요.
혹시 docker cp가 명령어가 호스트에서 도커까지 도달하는데 걸리는 시간이 더 길기 때문에 문제가 해결되는 걸까요?

만약 딜레이때문에 생기는 문제라면, 카피 직전에 sleep 함수 등을 써서 해결하는 방법은 어떨까요?

**Comment by KIMBIBLE** [comment]
> > 디스크 이미지 생성 시점과 카피 시점의 머징 과정 딜레이 때문에 발생.
> 
> 제가 제대로 이해한 것인지 모르겠지만, 디스크 이미지 생성 시간이, auto_build 소스코드가 카피를 수행하는 시점까지 도달하는데 걸리는 시간보다 오래걸리기 때문에 버그가 발생한다는 말씀이시죠?
> 
> 그렇다면 docker cp를 해도 결과는 똑같을 것같은데... 문제가 해결되는게 신기하네요.
> 혹시 docker cp가 명령어가 호스트에서 도커까지 도달하는데 걸리는 시간이 더 길기 때문에 문제가 해결되는 걸까요?
> 
> 만약 딜레이때문에 생기는 문제라면, 카피 직전에 sleep 함수 등을 써서 해결하는 방법은 어떨까요?

해당 이슈에 대해  설명을 부족하게 한 것 같아 추가 답변드립니다.

* 결론적으로 말씀드리자면, `docker cp` 명령은 기존 ubuntu 환경에서의 빌드 스크립트에서 해당 docker 컨테이너가 실행되고 있는 작업 공간의 host 경로를 구하기 위해  python docker 패키지를 활용하던 방법인 `get_dir = data['GraphDriver']['Data']['MergedDir']` 가 macOS 환경에서의 호환성이 유지되지 않아, 도커 컨테이너와 호스트 간 파일 복사를 위해 사용한 방법입니다.

* 해당 이슈에서 버그의 발생 원인은 auto_build 스크립트가 커널 빌드를 통해 디스크 이미지를 생성하고, 디스크 이미지 생성 결과가 실제 컨테이너에 새롭게 반영(base 컨테이너 레이어에 새롭게 추가된 레이어가 merge)되는 시간보다 빠르게 host에서 디스크 이미지를 복사하기 때문에 발생하는 문제입니다.

* 해당 과정은 아래의 예를 통해 설명드리겠습니다.

  * 먼저 컨테이너가 처음 실행되는 상황을 가정해보면, 아래의 try-except 문의  예외 처리 부분으로 코드의 흐름이 진행됩니다. 이때 `docker run` 명령을 통해 현재 빌드 환경이 구축되어 있는 컨테이너의 이미지를 통해 새로운 컨테이너가 생성됩니다.

  * 이러한 경우, 해당 컨테이너에 내부에는 이미지 생성 시 테스트 용으로 작업되어 있는 약 4.0KB `Disk.img` 파일이 있는 상태입니다.  https://github.com/0peratingSystem/Operating-System/blob/ad267b13311065b7135ecb96e1bb8a479893d4f9/AutoBuild_macOS.py#L38-L44

  * 이후 호스트의 빌드에 필요한 커널 소스코드를 컨테이너에 복사합니다. https://github.com/0peratingSystem/Operating-System/blob/ad267b13311065b7135ecb96e1bb8a479893d4f9/AutoBuild_macOS.py#L50-L52

  * 이어서 다음 라인부터 컨테이너 내부에서 빌드가 진행됩니다.
https://github.com/0peratingSystem/Operating-System/blob/ad267b13311065b7135ecb96e1bb8a479893d4f9/AutoBuild_macOS.py#L58-L60

  * 하지만 컨테이너에 빌드 요청이 종료되자마자 다음의 코드를 통해 컨테이너에서 생성된 이미지를 호스트로 복사를 요청합니다.
https://github.com/0peratingSystem/Operating-System/blob/ad267b13311065b7135ecb96e1bb8a479893d4f9/AutoBuild_macOS.py#L62-L64

  * 제가 해당 스크립트를 디버깅하였을 때, 해당 빌드 스크립를 처음 실행할 때 호스트로 복사된 디스크 이미지는 대략 4.0KB(해당 컨테이너 이미지에 원래 존재하던 이미지 크기와 동일)이었습니다. 하지만 스크립트 실행 후 해당 컨테이너에 `docker exec`명령을 통해 스크립트 종료시점의 컨테이너 파일 시스템을 확인해 본 결과, 해당 컨테이너 내에 정상적으로 빌드가 진행된 디스크 이미지가 존재하는 것을 확인하였습니다.

  * 따라서 이러한 원인이 발생하는 이유를 찾던 중  @KoreaSecurity 님께서 source copy가 `MergeDir` 을 기준으로 이루어지기 때문에 새롭게 생성된 레이어가 base 레이어에 merge되기 전에 복사를 진행하기 때문일 수 있다는 의견을 주셨습니다. https://github.com/0peratingSystem/Operating-System/blob/ad267b13311065b7135ecb96e1bb8a479893d4f9/Auto_Build_Prototype.py#L69-L71

  * 이를 제 개발환경인 macOS에서 테스트(`get_dir`의 결과가 macOS환경에서는 해당 docker 패키지를 통해 valid한 경로를 받아올 수 없기 때문에 `docker cp`를 사용) 해보기 위해, 빌드 명령 요청 이후 새롭게 생성된 레이어가 머지될 시간을 보장하기 위해 sleep을 줘서 테스트 해본 결과, 버그 해결이 가능했습니다.

  * 추가적으로 일단 새롭게 생성된 레이어가 머지될 시간은 어느 정도 필요할지 확실히 알 수 없어, 임의로 5초정도 sleep을 주었습니다.
