### ISSUE TITLE
Auto_Build_Prototype.py 실행을 위한 설치 요소

### ISSUE THREAD

**Issue by zj3t** [0peratingSystem/Operating-System#59]
ReadMe에 잘 나와있지만, 한번에 설치하는 게 어떨까해서 Install File을 만들어 두었습니다.

--> Auto_Install_pkg.py
`#!/bin/bash

#1.install Docker
sudo apt-get update -y
sudo apt-get install  -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

#2.Run Develop Environments
docker run -it koreasecurity/dev:os_dev

#3. install autobuild requirements
sudo apt-get -y install python3
pip3 install -r requirements.txt

pip3 install termcolor`

**Comment by KoreaSecurity** [comment]
Goof

**Comment by KoreaSecurity** [comment]
Good

**Comment by KIMBIBLE** [comment]
python3 패키지 중 `termcolor`는 현재 18ab01711c3b7d328df908e42cb33a575e079667 기준 패치가 완료되었습니다. 해당 부분 제외하고 기존 `scripts/install_ubuntu16.sh` 에 업데이트해서 develop 브랜치로 풀리퀘스트 보내주시면 될 것 같습니다.

추가적으로 해당 내용 ubuntu18 환경에서 작업하시는 분들도 해당 스크립트 테스트 후에 파일명을 `scripts/install_ubuntu18.sh`으로 설치 스크립트 하나 더 만들어주시면 좋을 것 같습니다.

**Comment by KIMBIBLE** [comment]
풀리퀘스트 보내주실 때 다음 사진처럼 `<#이슈번호> <내용>` 양식으로 보내주세요.

![image](https://user-images.githubusercontent.com/23338657/79300551-0fdd5300-7f22-11ea-8101-fdddd9c7b8b5.png)

**Comment by ghost** [comment]
> 
> 
> python3 패키지 중 `termcolor`는 현재 [18ab017](https://github.com/0peratingSystem/Operating-System/commit/18ab01711c3b7d328df908e42cb33a575e079667) 기준 패치가 완료되었습니다. 해당 부분 제외하고 기존 `scripts/install_ubuntu16.sh` 에 업데이트해서 develop 브랜치로 풀리퀘스트 보내주시면 될 것 같습니다.
> 
> 추가적으로 해당 내용 ubuntu18 환경에서 작업하시는 분들도 해당 스크립트 테스트 후에 파일명을 `scripts/install_ubuntu18.sh`으로 설치 스크립트 하나 더 만들어주시면 좋을 것 같습니다.

기존에 scripts/* 에 작성된 nasm이나 gcc 등 환경 설치에 관한 내용은 스크립트에서 제거하거나 백업할까요? 저희 이제 환경은 도커 컨테이너가 해결해주기 때문에 더 이상 필요는 없다고 생각합니다. 기존 내용은 제거하거나 백업으로 남겨두는게 어떨까요?

**Comment by KIMBIBLE** [comment]
네 말씀해주신대로 도커 컨테이너를 통해 빌드해서 환경 설정과 관련된 부분은 이제 제거해도 괜찮을 것 같습니다. 
그리고 백업은 어차피 커밋 로그로도 남아있어서 추가적인 백업은 필요하지 않을 것 같아요.
